- name: Delete all nodes
  gather_facts: False
  hosts: localhost
  tasks:
    - name: Build Web Nodes
      local_action:
        module: rax
        credentials: ~/.rackspace_cloud_credentials
        name: chrism-web-
        count: 2
        flavor: performance1-1
        image: ubuntu-1204-lts-precise-pangolin-pvhvm
        wait: yes
        state: absent
        group: web
        files:
          /root/.ssh/authorized_keys: ~/.ssh/id_rsa.pub
        networks:
          - private
          - public
      register: rax
    - name: Delete DB Nodes
      local_action:
        module: rax
        credentials: ~/.rackspace_cloud_credentials
        name: chrism-db-
        count: 1
        exact_count: yes
        flavor: performance1-1
        image: ubuntu-1204-lts-precise-pangolin-pvhvm
        wait: yes
        state: absent
        group: db
        files:
           /root/.ssh/authorized_keys: ~/.ssh/id_rsa.pub
        networks:
           - private
           - public
      register: rax
    - name: Delete App Nodes
      local_action:
        module: rax
        credentials: ~/.rackspace_cloud_credentials
        name: chrism-app-
        count: 2
        exact_count: yes
        flavor: performance1-1
        image: ubuntu-1204-lts-precise-pangolin-pvhvm
        wait: yes
        state: absent
        group: app
        files:
           /root/.ssh/authorized_keys: ~/.ssh/id_rsa.pub
        networks:
           - private
           - public
      register: rax
