- name: Delete db nodes
  gather_facts: False
  hosts: localhost
  tasks:
    - name: Delete db Nodes
      local_action:
        module: rax
        credentials: ~/.rackspace_cloud_credentials
        name: chrism-db-
        count: 1
        flavor: performance1-1
        image: ubuntu-1204-lts-precise-pangolin-pvhvm
        wait: yes
        state: absent
        group: db
        files:
          /root/.ssh/authorized_keys: ~/.ssh/id_rsa.pub
        networks:
          - private
          - public
      register: rax