- name: install mysql
  apt: name=mysql-server state=installed

- name: copy mysql config
  template: src=my.cnf dest=/etc/mysql/my.cnf
  notify: restart mysql

- name: copy firewall config
  template: src=ufw.sh dest=/root/ufw.sh

- name: set permissions for firewall script
  file: path=/root/ufw.sh owner=root group=root mode=0777

- name: run firewall config
  command: /root/ufw.sh

- name: delete firewall script
  command: /root/ufw.sh state=absent
