---
- name: Apt-get Update
  apt: update_cache=yes upgrade=dist

- name: Install Vim
  apt: name=vim state=installed

- name: Configure Vim as default
  shell: update-alternatives --set editor /usr/bin/vim.basic