- name: install nginx
  apt: name=nginx state=installed

- name: Copy nginx config
  template: src=default.conf dest=/etc/nginx/sites-enabled/wikistorm.conf
  notify: restart nginx
  
- name: copy firewall config
  template: src=ufw.sh dest=/root/ufw.sh

- name: set permissions for firewall script
  file: path=/root/ufw.sh owner=root group=root mode=0777

- name: run firewall config
  command: /root/ufw.sh

- name: delete firewall script
  file: path=/root/ufw.sh state=absent
