- name: Install RVM
  shell: curl -L https://get.rvm.io | bash -s stable --autolibs=3 creates=~/.rvm" executable=/bin/bash

- name: Install Ruby with RVM
  shell: /usr/local/rvm/bin/rvm install --default 2.1.1 creates=~/.rvm/rubies/2.1.1 executable=/bin/bash

- name: Set default Ruby version
  shell: bash -lc "/usr/local/rvm/bin/rvm --default use 2.1.1" executable=/bin/bash

- name: Create gemset for rails
  shell: bash -lc "/usr/local/rvm/bin/rvm gemset create rails" executable=/bin/bash

- name: Set default gemset to persist through reboot
  shell: bash -lc "/usr/local/rvm/bin/rvm use 2.1.1@rails --default" executable=/bin/bash

- name: Install gems needed
  shell: bash -lc "/usr/local/rvm/rubies/ruby-2.1.1/bin/gem install rails unicorn fog --no-ri --no-rdoc" executable=/bin/bash

- name: copy firewall config
  template: src=ufw.sh dest=/root/ufw.sh

- name: set permissions for firewall script
  file: path=/root/ufw.sh owner=root group=root mode=0777

- name: run firewall config
  command: /root/ufw.sh

- name: delete firewall script
  file: path=/root/ufw.sh state=absent

- name: create unicorn group
  group: name=unicorn gid=1150 state=present

- name: create unicorn user
  user: name=unicorn comment="Unicorn" uid=1150 group=unicorn home=/var/www/

- name: upload unicorn init file
  copy: src=unicorn dest=/etc/init.d/unicorn mode=755

- name: install git
  apt: name=git state=latest

- name: install nodejs
  apt: name=nodejs state=latest

- name: create wikistorm rails directory
  shell: bash -lc "/usr/local/rvm/gems/ruby-2.1.1/bin/rails new --force /var/www/wikistorm/"

- name: remove pre-generated app folder
  file: path=/var/www/wikistorm/app state=absent

- name: download wikistorm application
  git: repo=git://github.com/chris-mendoza/wikistorm.git
       dest=/var/www/wikistorm/app/

- name: add database configuration for wikistorm
  template: src=database.yml dest=/var/www/wikistorm/config/database.yml

- name: add routes configuration for wikistorm
  copy: src=routes.rb dest=/var/www/wikistorm/config/routes.rb
  
- name: add unicorn configuration to wikistorm config
  template: src=unicorn.rb dest=/var/www/wikistorm/config/unicorn.rb

- name: create unicorn directory
  file: path=/etc/unicorn state=directory

- name: add unicorn configuration to etc for init file
  copy: src=wikistorm.conf dest=/etc/unicorn/wikistorm.conf

- name: set permissions for wikistorm application
  file: path=/var/www/wikistorm owner=unicorn group=unicorn mode=644 recurse=yes