- name: Install RVM
  shell: \curl -L https://get.rvm.io | bash -s stable --autolibs=3 creates=~/.rvm

- name: Install Ruby with RVM
  shell: /usr/local/rvm/bin/rvm install --default 2.1.1 creates=~/.rvm/rubies/2.1.1

- name: Set default Ruby version
  shell: /usr/local/rvm/bin/rvm --default use 2.1.1

- name: Create gemset for rails
  shell: /usr/local/rvm/bin/rvm gemset create rails

- name: Set default gemset to persist through reboot
  shell: /usr/local/rvm/bin/rvm use 2.1.1@rails --default

- name: Install gems needed
  shell: /usr/local/rvm/rubies/ruby-2.1.1/bin/gem install rails unicorn 
