- name: Install RVM
  shell: bash -lc "\curl -L https://get.rvm.io | bash -s stable --autolibs=3 creates=~/.rvm"

- name: Install Ruby with RVM
  shell: bash -lc "/usr/local/rvm/bin/rvm install --default 2.1.1 creates=~/.rvm/rubies/2.1.1" 

- name: Set default Ruby version
  shell: bash -lc "/usr/local/rvm/bin/rvm --default use 2.1.1"

- name: Create gemset for rails
  shell: bash -lc "/usr/local/rvm/bin/rvm gemset create rails"

- name: Set default gemset to persist through reboot
  shell: bash -lc "/usr/local/rvm/bin/rvm use 2.1.1@rails --default"

- name: Install gems needed
  shell: bash -lc "/usr/local/rvm/rubies/ruby-2.1.1/bin/gem install rails unicorn --no-ri --no-rdoc"
