- name: Build DB Nodes
  gather_facts: False
  hosts: localhost
  tasks:
    - name: Build DB Node
      local_action:
        module: rax
        credentials: ~/.rackspace_cloud_credentials
        name: chrism-db-
        count: 1
        exact_count: yes
        flavor: performance1-1
        image: ubuntu-1204-lts-precise-pangolin-pvhvm
        wait: yes
        state: present
        group: db
        files:
           /root/.ssh/authorized_keys: ~/.ssh/id_rsa.pub
        networks:
           - private
           - public
      register: rax

    - name: Add created servers to db group
      local_action:
        module: add_host
        hostname: "{{ item.name }}"
        ansible_ssh_host: "{{ item.rax_accessipv4 }}"
        ansible_ssh_pass: "{{ item.rax_adminpass }} "
        groupname: db
      with_items: rax.success
      when: rax.action =='create'
