default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: wikistormdb
  password: omgbbq
  {% for host in groups['db'] %}
  host: {{ hostvars[host]['rax_addresses']['private'][0]['addr'] }}
  {% endfor %}
development:
  <<: *default
  database: wikistormdev

test:
  <<: *default
  database: wikistormtest

production:
  <<: *default
  database: wikistorm
