default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: wikistormdb
  password: 
  host: {{ database ip }}

development:
  <<: *default
  database: wikistormdev

test:
  <<: *default
  database: wikistormtest

production:
  <<: *default
  database: wikistorm
