- name: install mysql
  apt: name=mysql-server state=installed

- name: install python mysqldb connector
  apt: name=python-mysqldb state=latest

- name: copy mysql config
  template: src=my.cnf dest=/etc/mysql/my.cnf
  notify: restart mysql

- name: create wikistorm mysql user
  mysql_user: name=wikistormdb password=omgbbq host=% priv=wikistormdb.*:ALL state=present

- name: flush privileges after user addition
  shell: bash -lc "mysql -e 'flush privileges'"
  
- name: create database wikistormdb
  mysql_db: name=wikistormdb state=present

- name: copy firewall config
  template: src=ufw.sh dest=/root/ufw.sh

- name: set permissions for firewall script
  file: path=/root/ufw.sh owner=root group=root mode=0777

- name: run firewall config
  command: /root/ufw.sh

- name: delete firewall script
  file: path=/root/ufw.sh state=absent
