- name: Configure Web Servers
  hosts: web
  user: root
  roles:
    - common
    - web
- name: Configure DB Servers
  hosts: db
  user: root
  roles:
    - common
    - db
- name: Configure App Servers
  hosts: app
  user: root
  roles:
    - common
    - app
